platform :ios, '7.0'

pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~>2.6.1'
pod 'AFDownloadRequestOperation', '~>2.0.1'
pod 'BaiduMapKit', '~> 2.9.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'libqrencode', '~> 3.4.2'
pod 'UMengSocial', '~> 4.2.5'
pod 'UMengAnalytics', '~> 3.5.10'
pod 'Toast', '~> 2.4' 
pod 'IQKeyboardManager', '~> 3.2.4'
pod 'MJRefresh', '~> 2.4.7'
pod 'MJExtension', '~> 2.5.7'
pod 'JPush', '~> 1.8.7'
pod 'Masonry', '~> 0.6.2'
pod 'JSONModel', '~> 1.1.0'
pod 'REFrostedViewController', '~> 2.4.7'
pod 'MWPhotoBrowser'
pod 'EaseMobSDK'

#jiaxw